### ISSUE TITLE
Package causing compilation errors under Windows

### ISSUE THREAD

**Issue by ptkz** [discolabs/custard-js#26]
### Issue:
The package comes as an uncompiled source code, and the preferred solution to that is to add `exclude: /node_modules\/(?!@discolabs)/` to the webpack config. This causes a bunch of errors under windows. 
Colleagues with Linux, had no problem with this, but for me it seems that the exclude tweak is not working, since the discolabs source code won't get transpiled properly. 

Error thrown: 
[Disclabs error log.txt](https://github.com/discolabs/custard-js/files/4721343/Disclabs.error.log.txt)

### Environment:
OS: Windows 8.1
Node: 12.13.1 / 14.3.0  (tried with both)
NPM: 6.12.1 / 6.14.5 (tried with both)

**Comment by GorgonFreeman** [comment]
Hey Disco, this is John from Createur. This is the issue one of our devs on Windows came up against trying to work on a modified checkout that we'd used Custard.js on. At the moment they're planning on including it as an asset rather than a node module, which would also mean we'd need to do that with any checkout modifications from Submarine.js, and that could get messy considering the number of sites we're using it on.

Do you have an idea of how we can fix this issue without resorting to including the JS manually? I don't develop on Windows myself, but I imagine something about the syntax of the exclusion is the cause.

**Comment by gavinballard** [comment]
Thanks @ptkz and @GorgonFreeman.

Disco doesn't have a lot of experience building with Windows machines unfortunately. The error log provided has a lot of similar warnings/errors for other libraries though. Is this definitely a specific issue with Custard, or could it be more general?

**Comment by GorgonFreeman** [comment]
Hey @gavinballard, thanks for the reply, looks like we're not going to get anywhere quickly since I'm not on Windows either. We're going to try just removing that line on Windows environments for development, and having deployments done on other environments. I'll let you know how that goes.

**Comment by gavinballard** [comment]
Thanks @GorgonFreeman - sorry we can't be much help on this just now.
